language: python
python:
  - "3.7"
sudo: required
dist: xenial

group: edge

git:
  submodules: false

branches:
  except:
  - array

# addons:
#   apt:
#     packages:
#       - "python3"
#       - "python3-pip"

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/z3

before_cache:

env:
  global:
    - REPO=$TRAVIS_BUILD_DIR
    - TRAVIS_BUILD_APT_RETRIES_PERCENTAGE=100

matrix:
  include:
    - env: CABALVER=3.0 GHCVER=8.8.3
      compiler: "ghc-8.6.5"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc], config: {retries: true}}}
    - env: CABALVER=3.0 GHCVER=8.6.5
      compiler: "ghc-8.6.5"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc], config: {retries: true}}}
    - env: CABALVER=3.0 GHCVER=8.4.4
      compiler: "ghc-8.4.4"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.4.4,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc], config: {retries: true}}}

  allow_failures:
    # I know that some dependency triggers ghc panic in that version. / zilinc
  fast_finish: true

before_install:
 - unset CC
 - export ALEXVER=3.1.7
 - export HAPPYVER=1.19.5
 - export PATH=~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH
   # - pip --version
   # - sudo pip --version
 - pip install termcolor ruamel.yaml

install:
 # Get AutoCorres
 - wget http://ts.data61.csiro.au/projects/TS/autocorres/autocorres-1.6.tar.gz
 - tar -xf autocorres-1.6.tar.gz
 - mv autocorres-1.6 autocorres
 # setup Cabal
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal new-update # -v
 - cd cogent
 - "sed -i 's/^jobs:.*$/jobs: 2/' $HOME/.cabal/config"
 # - sed -i 's/^jobs:/ jobs:/' ${HOME}/.cabal/config

 - travis_wait 50 cabal new-install --installdir=$HOME/.cabal/bin --overwrite-policy=always;  # --enable-tests;

# Install z3
 - cd $REPO
 - git submodule update --init -- z3
 - cd z3
 - mkdir -p "$HOME"/z3
 - export PATH="$HOME/z3/bin:$PATH"
 - |
   if ! which z3;
   then # install z3
     python scripts/mk_make.py --prefix="$HOME/z3"
     cd build
     make
     make install
   fi
 - which z3 || travis_terminate 1

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - cd $REPO/cogent
 - cabal new-test test-quickcheck  # the other test is rarely affacted, so not enabled / zilinc
 # - cabal check
 - cabal new-haddock
 # Check if Cogent has been correctly installed
 - which cogent || travis_terminate 1
 # - echo 'Running tests'
 - make test-compiler
 # - echo 'Typechecking libgum'
 - make test-libgum
 # - echo 'Building Cogent examples'
 - make examples
 # - echo 'Generating ext2fs C code from Cogent'
 - cd $REPO/impl/fs/ext2/cogent && travis_wait make .c-gen
 # - echo 'Generating BilbyFs C code from Cogent'
 - cd $REPO/impl/fs/bilby/cogent && travis_wait make .c-gen

notifications:
  slack:
    rooms:
      - cogent-club:dUKOfdIU3BGsvalWStE0BCGG#ci
# EOF
